import { Injectable, OnModuleInit } from '@nestjs/common';
import { ConfigService } from '../config/config.service';
import { UserNotFoundException } from '../exceptions/user-not-found.exception';
import { EmailTakenException } from '../exceptions/email-taken.exception';
import * as AWS from '@aws-sdk/client-cognito-identity-provider';
import { v4 as uuidv4 } from 'uuid';

@Injectable()
export class CognitoService implements OnModuleInit {
	private client: any = null;

	constructor(private readonly configService: ConfigService) {}

	public async onModuleInit() {
		const region: string = await this.configService.get('AWS_REGION');
		const accessKey: string = await this.configService.get('AWS_ACCESS_KEY');
		const secretKey: string = await this.configService.get('AWS_SECRET_KEY');
		this.client = new AWS.CognitoIdentityProviderClient({
			region: region,
			credentials: {
				accessKeyId: accessKey,
				secretAccessKey: secretKey,
			},
		});
	}

	private async authUser(username: string, password: string): Promise<object> {
		const clientId: string = await this.configService.get('AWS_USER_POOL_CLIENT_ID');
		const command = new AWS.InitiateAuthCommand({
			AuthFlow: 'USER_PASSWORD_AUTH',
			ClientId: clientId,
			AuthParameters: {
				USERNAME: username,
				PASSWORD: password,
			},
		});

		const response: any = await this.client.send(command);
		const accessToken: string = response.AuthenticationResult.AccessToken;
		const refreshToken: string = response.AuthenticationResult.RefreshToken;

		return { accessToken, refreshToken };
	}

	public async signUp(email: string, password: string): Promise<any> {
		// Check whether the email is taken.
		let emailTaken: any = null;
		try {
			emailTaken = await this.getByEmail(email);
		} catch (error: any) {
			// Catch user not found exception.
		}
		if (emailTaken) {
			throw new EmailTakenException(email);
		}

		// Sign up with an autogenerated username, the email and the username of the email as the name.
		const clientId: string = await this.configService.get('AWS_USER_POOL_CLIENT_ID');
		const username: string = uuidv4();
		const name: string = email.substring(0, email.indexOf('@'));
		const command = new AWS.SignUpCommand({
			ClientId: clientId,
			Username: username,
			Password: password,
			UserAttributes: [
				{
					Name: 'email',
					Value: email,
				},
				{
					Name: 'name',
					Value: name,
				},
			],
		});

		await this.client.send(command);

		const user: any = await this.getByEmail(email);

		return user;
	}

	public async signDown(accessToken: string, password: string): Promise<any> {
		const user: any = await this.getMyUser(accessToken);

		await this.authUser(user.Username, password);

		await this.deleteMyUser(accessToken);

		return user;
	}

	public async signIn(email: string, password: string): Promise<object> {
		// Check whether the user exists.
		const user: any = await this.getByEmail(email);

		// Authenticate with username and password.
		const tokens: object = await this.authUser(user.Username, password);

		return tokens;
	}

	public async signOut(accessToken: string): Promise<boolean> {
		const command = new AWS.GlobalSignOutCommand({
			AccessToken: accessToken,
		});

		await this.client.send(command);

		return true;
	}

	public async refreshToken(refreshToken: string): Promise<string> {
		const clientId: string = await this.configService.get('AWS_USER_POOL_CLIENT_ID');
		const command = new AWS.InitiateAuthCommand({
			AuthFlow: 'REFRESH_TOKEN_AUTH',
			ClientId: clientId,
			AuthParameters: {
				REFRESH_TOKEN: refreshToken,
			},
		});

		const response: any = await this.client.send(command);
		const accessToken: string = response.AuthenticationResult.AccessToken;

		return accessToken;
	}

	public async forgotPassword(email: string): Promise<boolean> {
		const user: any = await this.getByEmail(email);

		const clientId: string = await this.configService.get('AWS_USER_POOL_CLIENT_ID');
		const command = new AWS.ForgotPasswordCommand({
			ClientId: clientId,
			Username: user.Username,
		});

		await this.client.send(command);

		return true;
	}

	public async changePassword(email: string, code: string, password: string): Promise<boolean> {
		const user: any = await this.getByEmail(email);

		const clientId: string = await this.configService.get('AWS_USER_POOL_CLIENT_ID');
		const command = new AWS.ConfirmForgotPasswordCommand({
			ClientId: clientId,
			Username: user.Username,
			ConfirmationCode: code,
			Password: password,
		});

		await this.client.send(command);

		return true;
	}

	public async verifyEmail(accessToken: string, code: string): Promise<boolean> {
		await this.getMyUser(accessToken);

		const command = new AWS.VerifyUserAttributeCommand({
			AccessToken: accessToken,
			AttributeName: 'email',
			Code: code,
		});

		await this.client.send(command);

		return true;
	}

	public async get(filter?: string): Promise<any[]> {
		const userPoolId: string = await this.configService.get('AWS_USER_POOL_ID');
		const params: any = {
			UserPoolId: userPoolId,
			Limit: 60, // Maximum number of users per API call.
			Filter: filter,
		};

		const users: any[] = [];
		while (true) {
			const command = new AWS.ListUsersCommand(params);

			const response: any = await this.client.send(command);
			const fetchedUsers: any[] = response.Users;

			users.push(...fetchedUsers);

			// Check if there are more users to retrieve.
			if (response.PaginationToken) {
				params.PaginationToken = response.PaginationToken;
			} else {
				break;
			}
		}

		return users;
	}

	public async getByEmail(email: string): Promise<any> {
		const users: any[] = await this.get(`email = "${email}"`);
		if (users.length !== 1) {
			throw new UserNotFoundException(email);
		}

		const user: any = users[0];

		return user;
	}

	public async getMyUser(accessToken: string): Promise<any> {
		const command = new AWS.GetUserCommand({
			AccessToken: accessToken,
		});

		const user: any = await this.client.send(command);

		return user;
	}

	public async updateMyUser(
		accessToken: string,
		name: string,
		surname: string,
		birthdate: string,
		country: string,
		timezone: string,
	): Promise<any> {
		const attributes = [];
		if (name !== undefined) {
			attributes.push({ Name: 'name', Value: name });
		}
		if (surname !== undefined) {
			attributes.push({ Name: 'family_name', Value: surname });
		}
		if (birthdate !== undefined) {
			attributes.push({ Name: 'birthdate', Value: birthdate });
		}
		if (country !== undefined) {
			attributes.push({ Name: 'locale', Value: country });
		}
		if (timezone !== undefined) {
			attributes.push({ Name: 'zoneinfo', Value: timezone });
		}

		const command = new AWS.UpdateUserAttributesCommand({
			AccessToken: accessToken,
			UserAttributes: attributes,
		});

		await this.client.send(command);

		return await this.getMyUser(accessToken);
	}

	public async updateMyEmail(accessToken: string, email: string): Promise<any> {
		const user: any = await this.getMyUser(accessToken);

		// Check whether the email is taken.
		const users: any[] = await this.get(`email = "${email}"`);
		if (users.length !== 0) {
			throw new EmailTakenException(email);
		}

		const userPoolId: string = await this.configService.get('AWS_USER_POOL_ID');
		const attributes = [{ Name: 'email', Value: email }];
		const command = new AWS.AdminUpdateUserAttributesCommand({
			UserPoolId: userPoolId,
			Username: user.Username,
			UserAttributes: attributes,
		});
		await this.client.send(command);

		return await this.getMyUser(accessToken);
	}

	public async updateMyPhone(accessToken: string, phone: string): Promise<any> {
		const user: any = await this.getMyUser(accessToken);

		const userPoolId: string = await this.configService.get('AWS_USER_POOL_ID');
		const attributes = [{ Name: 'phone_number', Value: phone }];
		const command = new AWS.AdminUpdateUserAttributesCommand({
			UserPoolId: userPoolId,
			Username: user.Username,
			UserAttributes: attributes,
		});
		await this.client.send(command);

		return await this.getMyUser(accessToken);
	}

	public async updateMyPassword(accessToken: string, currentPassword: string, newPassword: string): Promise<any> {
		const command = new AWS.ChangePasswordCommand({
			AccessToken: accessToken,
			PreviousPassword: currentPassword,
			ProposedPassword: newPassword,
		});

		await this.client.send(command);

		return await this.getMyUser(accessToken);
	}

	public async updateMyAvatar(accessToken: string, avatar: string): Promise<any> {
		const attributes = [{ Name: 'picture', Value: avatar }];
		const command = new AWS.UpdateUserAttributesCommand({
			AccessToken: accessToken,
			UserAttributes: attributes,
		});

		await this.client.send(command);

		return await this.getMyUser(accessToken);
	}

	public async deleteMyUser(accessToken: string): Promise<boolean> {
		const command = new AWS.DeleteUserCommand({
			AccessToken: accessToken,
		});

		await this.client.send(command);

		return true;
	}
}
