import { Injectable, OnModuleInit } from '@nestjs/common';
import { ConfigService } from '../../config/config.service';
import { Transform } from '../../../decorators/transform.decorator';
import { StatusBooleanToDto } from '../../../transforms/status-boolean-dto.transform';
import { CredentialsObjectToDto } from './transforms/credentials-object-dto.transform';
import { UserCognitoToDto } from './transforms/user-cognito-dto.transform';
import { StatusDto } from '../../../dtos/status.dto';
import { CredentialsDto } from '../../auth/credentials.dto';
import { UserDto } from '../../users/user.dto';
import { ResourceNotFoundException } from '../../../exceptions/resource-not-found.exception';
import { EmailTakenException } from '../../../exceptions/email-taken.exception';
import * as AWS from '@aws-sdk/client-cognito-identity-provider';
import { AuthUtils } from '../../../utils/auth.utils';

@Injectable()
export class CognitoService implements OnModuleInit {
	private client: AWS.CognitoIdentityProviderClient = null;

	constructor(private readonly configService: ConfigService) {}

	public async onModuleInit() {
		const region: string = await this.configService.get('AWS_REGION');
		const accessKey: string = await this.configService.get('AWS_ACCESS_KEY');
		const secretKey: string = await this.configService.get('AWS_SECRET_KEY');
		this.client = new AWS.CognitoIdentityProviderClient({
			region: region,
			credentials: {
				accessKeyId: accessKey,
				secretAccessKey: secretKey,
			},
		});
	}

	private async authUser(id: string, password: string): Promise<object> {
		const clientId: string = await this.configService.get('AWS_USER_POOL_CLIENT_ID');
		const input: AWS.InitiateAuthCommandInput = {
			AuthFlow: 'USER_PASSWORD_AUTH',
			ClientId: clientId,
			AuthParameters: {
				USERNAME: id,
				PASSWORD: password,
			},
		};

		const command = new AWS.InitiateAuthCommand(input);

		const output: AWS.InitiateAuthCommandOutput = await this.client.send(command);
		const accessToken: string = output.AuthenticationResult?.AccessToken ?? '';
		const refreshToken: string = output.AuthenticationResult?.RefreshToken ?? '';

		return { accessToken, refreshToken };
	}

	public async signUp(email: string, password: string): Promise<UserDto> {
		// Check whether the email is taken.
		let emailTaken: UserDto = null;
		try {
			emailTaken = await this.getByEmail(email);
		} catch (error: any) {
			// Catch user not found exception.
		}
		if (emailTaken) {
			throw new EmailTakenException(email);
		}

		// Sign up with an autogenerated username, the email and the username of the email as the name.
		const clientId: string = await this.configService.get('AWS_USER_POOL_CLIENT_ID');
		const username: string = AuthUtils.generateId();
		const name: string = email.substring(0, email.indexOf('@'));
		const input: AWS.SignUpCommandInput = {
			ClientId: clientId,
			Username: username,
			Password: password,
			UserAttributes: [
				{
					Name: 'email',
					Value: email,
				},
				{
					Name: 'name',
					Value: name,
				},
			],
		};

		const command = new AWS.SignUpCommand(input);

		await this.client.send(command);

		const user: UserDto = await this.getByEmail(email);

		return user;
	}

	public async signDown(accessToken: string, password: string): Promise<UserDto> {
		const user: UserDto = await this.getMyUser(accessToken);

		await this.authUser(user.id, password);

		await this.deleteMyUser(accessToken);

		return user;
	}

	@Transform(CredentialsObjectToDto)
	public async signIn(email: string, password: string): Promise<CredentialsDto> {
		// Check whether the user exists.
		const user: UserDto = await this.getByEmail(email);

		// Authenticate with username and password.
		const tokens: object = await this.authUser(user.id, password);

		return tokens as any;
	}

	@Transform(StatusBooleanToDto)
	public async signOut(accessToken: string): Promise<StatusDto> {
		const input: AWS.GlobalSignOutCommandInput = {
			AccessToken: accessToken,
		};

		const command = new AWS.GlobalSignOutCommand(input);

		await this.client.send(command);

		return true as any;
	}

	@Transform(CredentialsObjectToDto)
	public async refreshToken(refreshToken: string): Promise<CredentialsDto> {
		const clientId: string = await this.configService.get('AWS_USER_POOL_CLIENT_ID');
		const input: AWS.InitiateAuthCommandInput = {
			AuthFlow: 'REFRESH_TOKEN_AUTH',
			ClientId: clientId,
			AuthParameters: {
				REFRESH_TOKEN: refreshToken,
			},
		};

		const command = new AWS.InitiateAuthCommand(input);

		const output: AWS.InitiateAuthCommandOutput = await this.client.send(command);
		const accessToken: string = output.AuthenticationResult?.AccessToken ?? '';

		return { accessToken, refreshToken };
	}

	@Transform(StatusBooleanToDto)
	public async forgotPassword(email: string): Promise<StatusDto> {
		const user: UserDto = await this.getByEmail(email);

		const clientId: string = await this.configService.get('AWS_USER_POOL_CLIENT_ID');
		const input: AWS.ForgotPasswordCommandInput = {
			ClientId: clientId,
			Username: user.id,
		};

		const command = new AWS.ForgotPasswordCommand(input);

		await this.client.send(command);

		return true as any;
	}

	@Transform(StatusBooleanToDto)
	public async changePassword(email: string, code: string, password: string): Promise<StatusDto> {
		const user: UserDto = await this.getByEmail(email);

		const clientId: string = await this.configService.get('AWS_USER_POOL_CLIENT_ID');
		const input: AWS.ConfirmForgotPasswordCommandInput = {
			ClientId: clientId,
			Username: user.id,
			ConfirmationCode: code,
			Password: password,
		};

		const command = new AWS.ConfirmForgotPasswordCommand(input);

		await this.client.send(command);

		return true as any;
	}

	@Transform(StatusBooleanToDto)
	public async verifyEmail(accessToken: string, code: string): Promise<StatusDto> {
		await this.getMyUser(accessToken);

		const input: AWS.VerifyUserAttributeCommandInput = {
			AccessToken: accessToken,
			AttributeName: 'email',
			Code: code,
		};

		const command = new AWS.VerifyUserAttributeCommand(input);

		await this.client.send(command);

		return true as any;
	}

	@Transform(UserCognitoToDto)
	public async get(filter?: string): Promise<UserDto[]> {
		const userPoolId: string = await this.configService.get('AWS_USER_POOL_ID');
		const input: AWS.ListUsersCommandInput = {
			UserPoolId: userPoolId,
			Limit: 60, // Maximum number of users per API call.
			Filter: filter,
		};

		const users: AWS.UserType[] = [];
		while (true) {
			const command = new AWS.ListUsersCommand(input);

			const output: AWS.ListUsersCommandOutput = await this.client.send(command);

			if (output.Users) {
				users.push(...output.Users);
			}

			// Check if there are more users to retrieve.
			if (output.PaginationToken) {
				input.PaginationToken = output.PaginationToken;
			} else {
				break;
			}
		}

		return users as any;
	}

	public async getByEmail(email: string): Promise<UserDto> {
		const users: UserDto[] = await this.get(`email = "${email}"`);
		if (users.length !== 1) {
			throw new ResourceNotFoundException('User', { email });
		}

		const user: UserDto = users[0];

		return user;
	}

	@Transform(UserCognitoToDto)
	public async getMyUser(accessToken: string): Promise<UserDto> {
		const input: AWS.GetUserCommandInput = {
			AccessToken: accessToken,
		};

		const command = new AWS.GetUserCommand(input);

		const user: AWS.GetUserCommandOutput = await this.client.send(command);

		return user as any;
	}

	public async updateMyUser(
		accessToken: string,
		params?: {
			name?: string;
			surname?: string;
			birthdate?: string;
			country?: string;
			timezone?: string;
		},
	): Promise<UserDto> {
		const attributes = [];
		if (params.name !== undefined && params.name !== null) {
			attributes.push({ Name: 'name', Value: params.name });
		}
		if (params.surname !== undefined && params.surname !== null) {
			attributes.push({ Name: 'family_name', Value: params.surname });
		}
		if (params.birthdate !== undefined && params.birthdate !== null) {
			attributes.push({ Name: 'birthdate', Value: params.birthdate });
		}
		if (params.country !== undefined && params.country !== null) {
			attributes.push({ Name: 'locale', Value: params.country });
		}
		if (params.timezone !== undefined && params.timezone !== null) {
			attributes.push({ Name: 'zoneinfo', Value: params.timezone });
		}

		const input: AWS.UpdateUserAttributesCommandInput = {
			AccessToken: accessToken,
			UserAttributes: attributes,
		};

		const command = new AWS.UpdateUserAttributesCommand(input);

		await this.client.send(command);

		return await this.getMyUser(accessToken);
	}

	public async updateMyEmail(accessToken: string, email: string): Promise<UserDto> {
		const user: UserDto = await this.getMyUser(accessToken);

		// Check whether the email is taken.
		const users: any[] = await this.get(`email = "${email}"`);
		if (users.length !== 0) {
			throw new EmailTakenException(email);
		}

		const userPoolId: string = await this.configService.get('AWS_USER_POOL_ID');
		const attributes = [{ Name: 'email', Value: email }];
		const input: AWS.AdminUpdateUserAttributesCommandInput = {
			UserPoolId: userPoolId,
			Username: user.id,
			UserAttributes: attributes,
		};

		const command = new AWS.AdminUpdateUserAttributesCommand(input);

		await this.client.send(command);

		return await this.getMyUser(accessToken);
	}

	public async updateMyPhone(accessToken: string, phone: string): Promise<UserDto> {
		const user: UserDto = await this.getMyUser(accessToken);

		const userPoolId: string = await this.configService.get('AWS_USER_POOL_ID');
		const attributes = [{ Name: 'phone_number', Value: phone }];
		const input: AWS.AdminUpdateUserAttributesCommandInput = {
			UserPoolId: userPoolId,
			Username: user.id,
			UserAttributes: attributes,
		};

		const command = new AWS.AdminUpdateUserAttributesCommand(input);

		await this.client.send(command);

		return await this.getMyUser(accessToken);
	}

	public async updateMyPassword(accessToken: string, currentPassword: string, newPassword: string): Promise<UserDto> {
		const input: AWS.ChangePasswordCommandInput = {
			AccessToken: accessToken,
			PreviousPassword: currentPassword,
			ProposedPassword: newPassword,
		};

		const command = new AWS.ChangePasswordCommand(input);

		await this.client.send(command);

		return await this.getMyUser(accessToken);
	}

	public async updateMyAvatar(accessToken: string, avatar: string): Promise<UserDto> {
		const attributes = [{ Name: 'picture', Value: avatar }];
		const input: AWS.UpdateUserAttributesCommandInput = {
			AccessToken: accessToken,
			UserAttributes: attributes,
		};

		const command = new AWS.UpdateUserAttributesCommand(input);

		await this.client.send(command);

		return await this.getMyUser(accessToken);
	}

	@Transform(StatusBooleanToDto)
	public async deleteMyUser(accessToken: string): Promise<StatusDto> {
		const input: AWS.DeleteUserCommandInput = {
			AccessToken: accessToken,
		};

		const command = new AWS.DeleteUserCommand(input);

		await this.client.send(command);

		return true as any;
	}
}
